// packages/vue/src/components/InputRenderer.vue
<script setup lang="ts">
import { normalizeFieldValue } from 'pdyform/core';
import type { FieldRendererProps } from '../fieldComponentMap';
import Input from '../components/Input.vue';

const props = defineProps<FieldRendererProps>();
const emit = defineEmits<{ 'update:modelValue': [value: any] }>();

const handleInput = (nextValue: any) => {
  emit('update:modelValue', normalizeFieldValue(props.field, nextValue));
};
</script>

<template>
  <Input
    :id="fieldId"
    :type="field.type"
    :placeholder="field.placeholder"
    :disabled="field.disabled"
    :name="field.name"
    :modelValue="modelValue ?? ''"
    @update:modelValue="handleInput"
  />
</template>

// packages/react/src/components/InputRenderer.tsx
import React from 'react';
import { normalizeFieldValue } from 'pdyform/core';
import type { FieldRenderContext } from './types';
import { Input } from './Input';

const InputRenderer: React.FC<FieldRenderContext> = ({ field, value, onChange, onBlur, fieldId }) => {
  const handleChange = (nextValue: string) => {
    onChange(normalizeFieldValue(field, nextValue));
  };

  return (
    <Input
      id={fieldId}
      type={field.type}
      placeholder={field.placeholder}
      value={value ?? ''}
      onChange={(e) => handleChange(e.target.value)}
      onBlur={onBlur}
      disabled={field.disabled}
      name={field.name}
    />
  );
};

export default InputRenderer;
